---
- name: install pkg
  apt:
    name: 'chrony'
    state: present
  tags: [ ntp, chrony ]

- name: copy conf
  template:
    src: '{{ item.name }}.j2'
    dest: '/etc/chrony/{{ item.name }}'
    mode: '{{ item.mode }}'
  loop:
    - { name: chrony.conf, mode: '0644' }
    - { name: chrony.keys, mode: '0640' }
  notify: restart chrony
  tags: [ ntp, chrony ]

- name: enable&restart service
  service:
    name: chrony
    enabled: True
    state: restarted
  tags: [ ntp, chrony ]

...
