---
# tasks file for ansible-role-common

- hostname:
    name: "{{ ansible_hostname }}"

- name: Set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai

- name: Install a list of packages
  apt:
    state: absent
    pkg:
    - openssl

- name: Remove /etc/ssl/
  file:
    path: /etc/ssl/
    state: absent

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist

- name: Install a list of packages
  apt:
    pkg:
    - openssl
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg-agent 
    - software-properties-common
    - python3-jmespath
